"""Add create_at field

Revision ID: 7b7bf1e1c54f
Revises: 4baa99d0f6ae
Create Date: 2022-07-03 19:40:26.550551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7bf1e1c54f'
down_revision = '4baa99d0f6ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('word', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'created_at')
    op.drop_column('user', 'created_at')
    op.drop_column('tag', 'created_at')
    # ### end Alembic commands ###
