"""Add wordtag.user_id

Revision ID: 83fe6c102ee4
Revises: 40ea7e2c612a
Create Date: 2022-09-07 23:12:08.391290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83fe6c102ee4'
down_revision = '40ea7e2c612a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_tags', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'word_tags', ['word_id', 'tag_id', 'user_id'])
    op.create_foreign_key(None, 'word_tags', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word_tags', type_='foreignkey')
    op.drop_constraint(None, 'word_tags', type_='unique')
    op.drop_column('word_tags', 'user_id')
    # ### end Alembic commands ###
